version: "3.8"
services:
  #######################################
  # Backend | Directus
  #######################################
  {DOMAIN_NAME}-directus:
    container_name: {DOMAIN_NAME}-directus
    build:
      context: docker/
      dockerfile: Dockerfile
      args:
        DIRECTUS_VERSION: ${DIRECTUS_VERSION}
    env_file:
      - .env.local
    environment:
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - {DOMAIN_NAME}-db
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./database:/directus/database
      - ./templates:/directus/templates
    ports:
      - ${APP_PORT}:8055
    restart: always

  #######################################
  # Database
  #######################################
  {DOMAIN_NAME}-db:
    container_name: {DOMAIN_NAME}-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - {DOMAIN_NAME}_db_data:/var/lib/postgresql/data
    restart: always

  #######################################
  # pgAdmin
  #######################################
  {DOMAIN_NAME}-pgadmin:
    container_name: {DOMAIN_NAME}-pgadmin
    image: dpage/pgadmin4
    ports:
      - ${PMA_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - {DOMAIN_NAME}-db
    volumes:
      - {DOMAIN_NAME}_pgadmin_data:/var/lib/pgadmin
    restart: always

  #######################################
  # nginx
  #######################################
  {DOMAIN_NAME}-nginx:
    image: nginx:latest
    container_name: {DOMAIN_NAME}-nginx
    depends_on:
      - {DOMAIN_NAME}-directus
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    ports:
      - ${NGINX_PORT}:80
    restart: always

networks:
  default:
    name: {DOMAIN_NAME}_directus
    external: true

volumes:
  {DOMAIN_NAME}_db_data:
  {DOMAIN_NAME}_pgadmin_data:
